INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, 'Cool Project 1', 'Cool projects', 10000, 'yesterday', 'tomorrow'),
(2, 'Cool Project 2', 'Cool projects', 12000, 'yesterday', 'tomorrow'),
(3, 'Coolness', 'Cool projects', 13000, 'yesterday', 'tomorrow'),
(4, 'Cool Project 4', 'neat projects', 30000, 'yesterday', 'tomorrow'),
(5, 'Cool Project 6', 'neat projects', 10000, 'yesterday', 'tomorrow'),
(6, 'Awesome Project 1', 'neat projects', 5000, 'yesterday', 'tomorrow'),
(7, 'Why so many?', 'Really? projects', 1000000, 'yesterday', 'tomorrow'),
(8, 'Cool Project 8', 'Really? projects', 120000, 'yesterday', 'tomorrow'),
(9, 'Cool Project 9', 'Cool projects', 140000, 'yesterday', 'tomorrow'),
(10, 'Cool Project 10', 'Cool projects', 10000, 'yesterday', 'tomorrow');
